/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ExampleCom: typeof import('./src/components/ExampleCom.vue')['default']
    Hearder: typeof import('./src/components/Layout/vueHearder.vue')['default']
    Layout: typeof import('./src/components/Layout/vueLayout.vue')['default']
    QuestionControl: typeof import('./src/components/QuestionControl.vue')['default']
    QuestionCover: typeof import('./src/components/QuestionCover.vue')['default']
    QuestionNav: typeof import('./src/components/QuestionNav.vue')['default']
    QuestionShow: typeof import('./src/components/QuestionShow.vue')['default']
    QustionCover: typeof import('./src/components/QustionCover.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShrinkButton: typeof import('./src/components/ShrinkButton.vue')['default']
    VLayout: typeof import('./src/components/Layout/vueLayout.vue')['default']
    VueHearder: typeof import('./src/components/Layout/vueHearder.vue')['default']
    VueLayout: typeof import('./src/components/Layout/vueLayout.vue')['default']
    VuwLayout: typeof import('./src/components/Layout/vueLayout.vue')['default']
  }
}
